# Generated by Django 5.2.4 on 2025-07-31 02:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='ผู้ใช้')),
                ('user_type', models.CharField(choices=[('STUDENT', 'นิสิต'), ('INSTRUCTOR', 'อาจารย์'), ('STAFF', 'เจ้าหน้าที่')], default='STUDENT', max_length=10, verbose_name='ประเภทผู้ใช้')),
                ('staff_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='ชื่อเจ้าหน้าที่')),
                ('student_id', models.CharField(blank=True, max_length=15, null=True, unique=True, verbose_name='รหัสนิสิต')),
                ('student_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='ชื่อนิสิต')),
                ('student_status', models.CharField(choices=[('STUDYING', 'กำลังศึกษา'), ('ON_LEAVE', 'พักการเรียน'), ('GRADUATED', 'สำเร็จการศึกษา')], default='STUDYING', max_length=10, verbose_name='สถานะนิสิต')),
                ('instructor_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='ชื่ออาจารย์')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.branch', verbose_name='สาขาวิชา')),
            ],
        ),
    ]
