# Generated by Django 5.2.4 on 2025-08-06 04:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_course_department'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='student_name',
        ),
        migrations.AddField(
            model_name='profile',
            name='acdemic_title',
            field=models.CharField(blank=True, choices=[('PROFESSOR', 'ศาสตราจารย์'), ('ASSOCIATE_PROFESSOR', 'รองศาสตราจารย์'), ('ASSISTANT_PROFESSOR', 'ผู้ช่วยศาสตราจารย์')], max_length=50, null=True, verbose_name='ตำแหน่งทางวิชาการ'),
        ),
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='ที่อยู่'),
        ),
        migrations.AddField(
            model_name='profile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='วันเกิด'),
        ),
        migrations.AddField(
            model_name='profile',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.department', verbose_name='ภาควิชา'),
        ),
        migrations.AddField(
            model_name='profile',
            name='first_name_th',
            field=models.CharField(default='-', max_length=30, verbose_name='ชื่อ'),
        ),
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('MALE', 'ชาย'), ('FEMALE', 'หญิง'), ('OTHER', 'อื่นๆ')], max_length=10, null=True, verbose_name='เพศ'),
        ),
        migrations.AddField(
            model_name='profile',
            name='job_title',
            field=models.CharField(blank=True, choices=[('REGISTRATION_OFFICER', 'เจ้าหน้าที่ทะเบียน')], max_length=100, null=True, verbose_name='ตำแหน่งงาน'),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_name_th',
            field=models.CharField(default='-', max_length=30, verbose_name='นามสกุล'),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='เบอร์โทรศัพท์'),
        ),
    ]
