# Generated by Django 5.2.4 on 2025-08-06 16:03

import django.core.validators
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_profile_student_name_profile_acdemic_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='instructor_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='staff_name',
        ),
        migrations.AlterField(
            model_name='profile',
            name='first_name_th',
            field=models.CharField(default='-', validators=[django.core.validators.MaxLengthValidator(30, message='ชื่อต้องไม่เกิน 30 ตัวอักษร'), django.core.validators.RegexValidator(message='ชื่อต้องประกอบด้วยตัวอักษรและไม่มีเว้นวรรค', regex='^[A-Za-z]+$')], verbose_name='ชื่อ'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_name_th',
            field=models.CharField(default='-', validators=[django.core.validators.MaxLengthValidator(30, message='นามสกุลต้องไม่เกิน 30 ตัวอักษร')], verbose_name='นามสกุล'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='เบอร์โทรศัพท์'),
        ),
    ]
