# Generated by Django 5.2.4 on 2025-08-06 16:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_profile_instructor_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='first_name_th',
            field=models.CharField(default='-', validators=[django.core.validators.RegexValidator(message='ชื่อต้องประกอบด้วยตัวอักษรภาษาไทยเท่านั้น', regex='^[ก-ฮ]+$')], verbose_name='ชื่อ'),
        ),
    ]
