# Generated by Django 5.2.4 on 2025-08-06 16:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_profile_first_name_th'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='first_name_th',
            field=models.CharField(default='-', validators=[django.core.validators.RegexValidator(message='กรุณาป้อนเป็นตัวอักษรภาษาไทยเท่านั้น', regex='^[ก-ฮ]+$')], verbose_name='ชื่อ'),
        ),
    ]
