# Generated by Django 5.2.4 on 2025-08-06 17:57

import django.core.validators
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_profile_first_name_th'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='acdemic_title',
            field=models.CharField(blank=True, choices=[('PROFESSOR', 'ศาสตราจารย์'), ('ASSOCIATE_PROFESSOR', 'รองศาสตราจารย์'), ('ASSISTANT_PROFESSOR', 'ผู้ช่วยศาสตราจารย์'), ('LECTURER', 'อาจารย์')], max_length=50, null=True, verbose_name='ตำแหน่งทางวิชาการ'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='first_name_th',
            field=models.CharField(blank=True, max_length=100, validators=[django.core.validators.RegexValidator(message='กรุณาป้อนเป็นตัวอักษรภาษาไทยเท่านั้น', regex='^[\\u0E00-\\u0E7F]+$')], verbose_name='ชื่อ (ภาษาไทย)'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_name_th',
            field=models.CharField(blank=True, max_length=100, validators=[django.core.validators.RegexValidator(message='กรุณาป้อนเป็นตัวอักษรภาษาไทยเท่านั้น', regex='^[\\u0E00-\\u0E7F]+$')], verbose_name='นามสกุล (ภาษาไทย)'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region='TH', verbose_name='เบอร์โทรศัพท์'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='student_id',
            field=models.CharField(blank=True, max_length=8, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='รหัสนิสิตต้องเป็นตัวเลข 8 หลัก', regex='^\\d{8}$')], verbose_name='รหัสนิสิต'),
        ),
    ]
