# Generated by Django 5.2.4 on 2025-08-10 10:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_profile_acdemic_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.TextField(blank=True, help_text='กรอกที่อยู่เป็นภาษาไทย ใช้ตัวเลขและเครื่องหมาย /,.-', null=True, validators=[django.core.validators.RegexValidator(message='ที่อยู่ต้องเป็นภาษาไทยและอักขระที่กำหนดเท่านั้น', regex='^[ก-๙0-9/\\s,.-]+$')], verbose_name='ที่อยู่'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='first_name_th',
            field=models.CharField(blank=True, max_length=100, validators=[django.core.validators.RegexValidator(message='กรุณาป้อนเป็นตัวอักษรภาษาไทยเท่านั้น', regex='^[\\u0E00-\\u0E7F\\s]+$')], verbose_name='ชื่อ (ภาษาไทย)'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_name_th',
            field=models.CharField(blank=True, max_length=100, validators=[django.core.validators.RegexValidator(message='กรุณาป้อนเป็นตัวอักษรภาษาไทยเท่านั้น', regex='^[\\u0E00-\\u0E7F\\s]+$')], verbose_name='นามสกุล (ภาษาไทย)'),
        ),
    ]
