# Generated by Django 5.2.4 on 2025-08-14 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_profile_address_alter_profile_first_name_th_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='student_status',
            field=models.CharField(blank=True, choices=[('STUDYING', 'กำลังศึกษา'), ('ON_LEAVE', 'พักการเรียน'), ('GRADUATED', 'สำเร็จการศึกษา')], max_length=10, null=True, verbose_name='สถานะนิสิต'),
        ),
    ]
