# Generated by Django 5.2.4 on 2025-08-14 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_profile_student_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='name_title',
            field=models.CharField(blank=True, choices=[('MR', 'นาย'), ('MRS', 'นาง'), ('MS', 'นางสาว'), ('DR', 'ดร.')], max_length=10, null=True, verbose_name='คำนำหน้าชื่อ'),
        ),
    ]
