# Generated by Django 5.2.4 on 2025-07-31 02:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='ชื่อภาควิชา')),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='ชื่อคณะ')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credits', models.PositiveSmallIntegerField(default=3, verbose_name='หน่วยกิต')),
                ('is_active', models.BooleanField(default=True, verbose_name='สถานะเปิดใช้งาน')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='รหัสวิชา')),
                ('name', models.CharField(max_length=200, verbose_name='ชื่อวิชา')),
                ('description', models.TextField(blank=True, null=True, verbose_name='คำอธิบายวิชา')),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='courses.department', verbose_name='ภาควิชา')),
            ],
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='ชื่อสาขาวิชา')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='courses.department', verbose_name='สังกัดภาควิชา')),
            ],
        ),
        migrations.AddField(
            model_name='department',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='courses.faculty', verbose_name='สังกัดคณะ'),
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building', models.CharField(max_length=100, verbose_name='ชื่อตึก')),
                ('room_number', models.CharField(max_length=20, verbose_name='เลขห้อง')),
            ],
            options={
                'unique_together': {('building', 'room_number')},
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_number', models.CharField(max_length=5, verbose_name='กลุ่มเรียน (Sec)')),
                ('capacity', models.PositiveIntegerField(default=30, verbose_name='จำนวนที่รับ')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='courses.course', verbose_name='รายวิชา')),
                ('instructors', models.ManyToManyField(blank=True, limit_choices_to={'profile__user_type': 'INSTRUCTOR'}, related_name='taught_sections', to=settings.AUTH_USER_MODEL, verbose_name='อาจารย์ผู้สอน')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.room', verbose_name='ห้องเรียน')),
                ('students', models.ManyToManyField(blank=True, related_name='enrolled_sections', to=settings.AUTH_USER_MODEL, verbose_name='นิสิตที่ลงทะเบียน')),
            ],
        ),
        migrations.CreateModel(
            name='ClassTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('MON', 'วันจันทร์'), ('TUE', 'วันอังคาร'), ('WED', 'วันพุธ'), ('THU', 'วันพฤหัสบดี'), ('FRI', 'วันศุกร์'), ('SAT', 'วันเสาร์'), ('SUN', 'วันอาทิตย์')], max_length=3)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_times', to='courses.section')),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(verbose_name='ปีการศึกษา (พ.ศ.)')),
                ('semester', models.PositiveSmallIntegerField(choices=[(1, 'ภาคเรียนที่ 1'), (2, 'ภาคเรียนที่ 2'), (3, 'ภาคเรียนฤดูร้อน')], verbose_name='ภาคเรียน')),
                ('start_date', models.DateField(verbose_name='วันเปิดภาคเรียน')),
                ('end_date', models.DateField(verbose_name='วันสิ้นสุดภาคเรียน')),
            ],
            options={
                'unique_together': {('year', 'semester')},
            },
        ),
        migrations.AddField(
            model_name='section',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sections', to='courses.semester', verbose_name='ภาคเรียน'),
        ),
        migrations.AlterUniqueTogether(
            name='section',
            unique_together={('course', 'semester', 'section_number')},
        ),
    ]
