# Generated by Django 5.2.4 on 2025-08-06 17:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_course_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='credits',
            field=models.PositiveSmallIntegerField(default=3, validators=[django.core.validators.MinValueValidator(1, message='หน่วยกิตต้องมีค่าอย่างน้อย 1'), django.core.validators.MaxValueValidator(9, message='หน่วยกิตต้องมีค่าไม่เกิน 9')], verbose_name='หน่วยกิต'),
        ),
        migrations.AlterField(
            model_name='section',
            name='capacity',
            field=models.PositiveIntegerField(default=30, validators=[django.core.validators.MinValueValidator(1, message='จำนวนที่รับต้องมีค่าอย่างน้อย 1')], verbose_name='จำนวนที่รับ'),
        ),
        migrations.AlterField(
            model_name='section',
            name='section_number',
            field=models.CharField(max_length=3, validators=[django.core.validators.RegexValidator(message='กรุณากรอกหมายเลขกลุ่มเรียนเป็นตัวเลข', regex='^[0-9]$')], verbose_name='กลุ่มเรียน (Sec)'),
        ),
        migrations.AlterField(
            model_name='semester',
            name='year',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(2560, message='ปีการศึกษาต้องไม่เก่ากว่าปี 2560')], verbose_name='ปีการศึกษา (พ.ศ.)'),
        ),
    ]
