# Generated by Django 5.2.4 on 2025-08-10 10:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_course_credits_alter_section_capacity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='code',
            field=models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='รหัสวิชาต้องเป็นตัวเลข 8 หลัก', regex='^\\d{8}$')], verbose_name='รหัสวิชา'),
        ),
        migrations.AlterField(
            model_name='course',
            name='credits',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1, message='หน่วยกิตต้องมีค่าอย่างน้อย 1'), django.core.validators.MaxValueValidator(9, message='หน่วยกิตต้องมีค่าไม่เกิน 9')], verbose_name='หน่วยกิต'),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(blank=True, null=True, validators=[django.core.validators.RegexValidator(message='คำอธิบายวิชาต้องประกอบด้วยตัวอักษรภาษาไทย ภาษาอังกฤษ ตัวเลข และเครื่องหมาย -(),.เท่านั้น', regex='^[ก-์A-Za-z0-9\\s\\-(),.]+$')], verbose_name='คำอธิบายวิชา'),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=200, validators=[django.core.validators.RegexValidator(message='ชื่อวิชาต้องประกอบด้วยตัวอักษรภาษาไทย ภาษาอังกฤษ ตัวเลข และเครื่องหมาย -(),เท่านั้น', regex='^[ก-์A-Za-z0-9\\s\\-(),]+$')], verbose_name='ชื่อวิชา'),
        ),
        migrations.AlterField(
            model_name='section',
            name='capacity',
            field=models.PositiveIntegerField(default=30, validators=[django.core.validators.MinValueValidator(1, message='จำนวนที่รับต้องมีค่าอย่างน้อย 1'), django.core.validators.MaxValueValidator(200, message='จำนวนที่รับต้องไม่เกิน 200 คน')], verbose_name='จำนวนที่รับ'),
        ),
        migrations.AlterField(
            model_name='section',
            name='section_number',
            field=models.CharField(max_length=3, validators=[django.core.validators.RegexValidator(message='กรุณากรอกหมายเลขกลุ่มเรียนเป็นตัวเลข 1-99', regex='^[1-9][0-9]?$')], verbose_name='กลุ่มเรียน (Sec)'),
        ),
    ]
