# Generated by Django 5.2.4 on 2025-08-14 02:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_course_code_alter_course_credits_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='name',
            field=models.CharField(max_length=200, unique=True, validators=[django.core.validators.RegexValidator(message='กรุณาป้อนชื่อสาขาวิชาเป็นภาษาไทยเท่านั้น', regex='^[ก-์\\s]+$')], verbose_name='ชื่อสาขาวิชา'),
        ),
        migrations.AlterField(
            model_name='classtime',
            name='end_time',
            field=models.TimeField(verbose_name='เวลาเลิกเรียน'),
        ),
        migrations.AlterField(
            model_name='classtime',
            name='start_time',
            field=models.TimeField(verbose_name='เวลาเริ่มเรียน'),
        ),
        migrations.AlterField(
            model_name='course',
            name='code',
            field=models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='รหัสวิชาต้องเป็นตัวเลข 6 หลัก', regex='^\\d{6}$')], verbose_name='รหัสวิชา'),
        ),
        migrations.AlterField(
            model_name='course',
            name='credits',
            field=models.PositiveSmallIntegerField(default=3, validators=[django.core.validators.MinValueValidator(1, message='หน่วยกิตต้องมีค่าอย่างน้อย 1'), django.core.validators.MaxValueValidator(9, message='หน่วยกิตต้องมีค่าไม่เกิน 9')], verbose_name='หน่วยกิต'),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=200, unique=True, validators=[django.core.validators.RegexValidator(message='กรุณาป้อนชื่อภาควิชาเป็นภาษาไทยเท่านั้น', regex='^[ก-์\\s]+$')], verbose_name='ชื่อภาควิชา'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='name',
            field=models.CharField(max_length=200, unique=True, validators=[django.core.validators.RegexValidator(message='กรุณาป้อนชื่อคณะเป็นภาษาไทยเท่านั้น', regex='^[ก-์\\s]+$')], verbose_name='ชื่อคณะ'),
        ),
        migrations.AlterField(
            model_name='room',
            name='building',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='ชื่อตึกต้องประกอบด้วยตัวอักษรภาษาไทย ภาษาอังกฤษ ตัวเลข และเครื่องหมาย - เท่านั้น', regex='^[ก-์A-Za-z0-9\\s\\-]+$')], verbose_name='ชื่อตึก'),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_number',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='เลขห้องต้องประกอบด้วยตัวอักษรภาษาอังกฤษ ตัวเลข และเครื่องหมาย - เท่านั้น', regex='^[A-Za-z0-9\\-]+$')], verbose_name='เลขห้อง'),
        ),
    ]
