# Generated by Django 5.2.4 on 2025-08-14 03:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_alter_branch_name_alter_classtime_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classtime',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_times', to='courses.section', verbose_name='กลุ่มเรียน'),
        ),
    ]
