# Generated by Django 5.2.4 on 2025-08-19 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_alter_classtime_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classtime',
            name='day',
            field=models.CharField(choices=[('MON', 'วันจันทร์'), ('TUE', 'วันอังคาร'), ('WED', 'วันพุธ'), ('THU', 'วันพฤหัสบดี'), ('FRI', 'วันศุกร์'), ('SAT', 'วันเสาร์'), ('SUN', 'วันอาทิตย์')], max_length=3, verbose_name='วัน'),
        ),
    ]
